server:
  port: 8080

spring:
  application:
    name: LookFor
  main:
    banner-mode: off

  # 공식 문서 기반 설정
  ai:
    mcp:
      server:
        stdio: false
        enabled: true
        sse-message-endpoint: /mcp/message
        name: mcp-look-for
        type: sync
        version: 0.0.1
        sse-endpoint: /sse
#        streamable-http:
#          mcp-endpoint: /mcp

gov:
  share:
    api:
      host: "https://www.eshare.go.kr"
      key: "f1b4c71d4f773ba6bff8e6079e0f956b"